language: python

python:
  - "2.7"

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy3
  - TOXENV=flake8

# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: pypy-5.4
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox
