language: python

python:
  - "2.7"

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=flake8

# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox
